### ISSUE TITLE
Are there plans to release elfcat?

### ISSUE THREAD

**Issue by krytarowski** [randomstuff/elfcat#2]
I find it useful and easier to use than `objdump`(1)-like utilities.

I'm a volunteer to package it for pkgsrc (NetBSD).

This code is also very good source of how to get to a section in an ELF file.

Thanks!

**Comment by randomstuff** [comment]
Well I did not really have any plan until now because it was good anough for my personal use case but I'm willing to irong things out in order to have a release. For a release, I guess I'd want to :
- (maybe) be slightly more flexible in the argument processing (?) (currently the ELF file name must be passed before the other arguments) but I kind of like have a dead-simple code ;
- add a manpage.

As for packaging for NetBSD, I probably won't work on this myself (I'd probably start packaging for OSes I'm actively usings) but if you want to work on it I'd ba happy to do/merge whatever I can :)

**Comment by krytarowski** [comment]
`getopt_long`(3) is a standard in BSD and GNU, no need to reinvent the wheel.

I will take happily the pkgsrc/NetBSD part.

**Comment by krytarowski** [comment]
After merging autotools the last thing is syncing: `elfcat ./foo --program-index` between manuals. Whether it accepts a parameter. What's the final decision? Thanks.

Otherwise it looks ready to be released.

It would be nice to add the following text to README.

Installation on NetBSD from prebuilt packages:

```
pkgin install elfcat
```

Installation from sources

```
cd /usr/pkgsrc/devel/elfcat && make install
```

**Comment by randomstuff** [comment]
I guess I should `s/aha/elfcat/` :)

**Comment by krytarowski** [comment]
Right. It was copy-pasted. I will edit the above post.

**Comment by krytarowski** [comment]
Done!

**Comment by randomstuff** [comment]
I changed the version in preparation of a 1.0.0 release. If you do not see anything missing, I'll tag v1.0.0.

**Comment by randomstuff** [comment]
I tagged v1.0.0. \o/ Unless you think something is missing I'll close this. Thanks for the work.

**Comment by krytarowski** [comment]
Thank you!

It has been imported to pkgsrc-wip: https://wip.pkgsrc.org/cgi-bin/gitweb.cgi?p=pkgsrc-wip.git;a=commitdiff;h=8c4dd122b8b0ce7b7088ab97fb109d9fa81033b9

I will move it to the main pkgsrc repository in the coming days.

**Comment by randomstuff** [comment]
Nice!
